api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Infrastructure/UI/Http/Rest/Resource']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
