version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '4306:3306'
    volumes:
      - mysql:/var/lib/mysql

  php:
    container_name: php
    build:
      context: docker/php
      args:
        TIMEZONE: ${TIMEZONE}
        USER_NAME: ${USER_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '443:443'
    volumes:
      - .:/var/www/marketplace
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/marketplace
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

volumes:
  mysql:
