# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
  gke: circleci/gcp-gke@1.4.0 # Use the GCP GKE orb in your config
  
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      # Specify the version you desire here
      - image: cimg/php:8.1-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - browser-tools/install-browser-tools

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      #- run: sudo docker-php-ext-install zip

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # TODO prepare the database
  
      - run:
          name: "Run tests with coverage"
          command: |
            mkdir -p ~/phpunit
            phpdbg -qrr bin/phpunit --coverage-html build/coverage-report --log-junit ~/phpunit/junit.xml tests
          when: always
          environment:
            XDEBUG_MODE: coverage
      - store_artifacts:
          path:  build/coverage-report
      - store_test_results:
          path: ~/phpunit
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
  main:
    jobs:
      - gke/publish-and-rollout-image:
          requires:
            - build
          cluster: marketplace-cluster-1 # name of GKE cluster to be created
          container: nginx # name of your Kubernetes container
          deployment: nginx-deployment # name of your Kubernetes deployment
          image: nginx:stable-alpine # name of your Docker image
