apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-ingress
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 8080