# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Product\Domain\:
        resource: '../src/Product/Domain/*Service.php'
    App\Product\Application\Command\:
        resource: '../src/Product/Application/Command/*CommandHandler.php'
    App\Infrastructure\:
        resource: '../src/Infrastructure/'
        exclude:
            - '../src/Infrastructure/Persistence/Doctrine/mappings'
            - '../src/Infrastructure/Persistence/Doctrine/migrations'
            - '../src/Infrastructure/UI/Http/Rest/Resource'
            - '../src/Infrastructure/UI/Http/Web/templates'

    App\Product\Domain\ProductRepository:
        alias: App\Infrastructure\Persistence\Doctrine\DoctrineProductRepository
    App\Product\Application\Query\QueryService:
        alias: App\Infrastructure\Persistence\Doctrine\DoctrineProductQueryService

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
